# Generated by Django 2.1.5 on 2019-01-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(help_text='邮箱', max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.CharField(help_text='信息', max_length=300, verbose_name='信息'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(help_text='lead名字', max_length=100, verbose_name='lead名字'),
        ),
    ]
